
import { DiscographyData } from "./types";

export const discographyByDecade: DiscographyData = {
  "1980s": [
    { artist: "Slayer", title: "Reign in Blood", year: 1986, notable: true },
    { artist: "Beastie Boys", title: "Licensed to Ill", year: 1986, notable: true },
    { artist: "Run-DMC", title: "Raising Hell", year: 1986, notable: true },
    { artist: "Public Enemy", title: "It Takes a Nation of Millions to Hold Us Back", year: 1988, notable: true },
    { artist: "Public Enemy", title: "Yo! Bum Rush the Show", year: 1987 },
    { artist: "The Cult", title: "Electric", year: 1987 },
    { artist: "Danzig", title: "Danzig", year: 1988 },
    { artist: "Masters of Reality", title: "Masters of Reality", year: 1988 },
    { artist: "Slayer", title: "South of Heaven", year: 1988 },
    { artist: "Red Hot Chili Peppers", title: "Mother's Milk", year: 1989 },
    { artist: "Andrew Dice Clay", title: "Dice", year: 1989 },
  ],
  "1990s": [
    { artist: "Red Hot Chili Peppers", title: "Blood Sugar Sex Magik", year: 1991, notable: true },
    { artist: "Danzig", title: "Danzig II: Lucifuge", year: 1990 },
    { artist: "Slayer", title: "Seasons in the Abyss", year: 1990 },
    { artist: "Andrew Dice Clay", title: "The Day the Laughter Died", year: 1990 },
    { artist: "Danzig", title: "Danzig III: How the Gods Kill", year: 1992 },
    { artist: "Sir Mix-a-Lot", title: "Mack Daddy", year: 1992 },
    { artist: "Mick Jagger", title: "Wandering Spirit", year: 1993 },
    { artist: "The Four Horsemen", title: "Gettin' Pretty Good... at Barely Gettin' By", year: 1993 },
    { artist: "Johnny Cash", title: "American Recordings", year: 1994, notable: true },
    { artist: "Tom Petty", title: "Wildflowers", year: 1994, notable: true },
    { artist: "Slayer", title: "Divine Intervention", year: 1994 },
    { artist: "AC/DC", title: "Ballbreaker", year: 1995 },
    { artist: "Red Hot Chili Peppers", title: "One Hot Minute", year: 1995 },
    { artist: "Donovan", title: "Sutras", year: 1996 },
    { artist: "Johnny Cash", title: "Unchained", year: 1996, notable: true },
    { artist: "Melanie C", title: "Northern Star", year: 1999 },
    { artist: "System of a Down", title: "System of a Down", year: 1998 },
    { artist: "Red Hot Chili Peppers", title: "Californication", year: 1999, notable: true },
  ],
  "2000s": [
    { artist: "Johnny Cash", title: "American III: Solitary Man", year: 2000, notable: true },
    { artist: "System of a Down", title: "Toxicity", year: 2001, notable: true },
    { artist: "System of a Down", title: "Steal This Album!", year: 2002 },
    { artist: "Johnny Cash", title: "American IV: The Man Comes Around", year: 2002, notable: true },
    { artist: "Red Hot Chili Peppers", title: "By the Way", year: 2002 },
    { artist: "Weezer", title: "Maladroit", year: 2002 },
    { artist: "The Mars Volta", title: "De-Loused in the Comatorium", year: 2003 },
    { artist: "Jay-Z", title: "99 Problems (single)", year: 2003, notable: true },
    { artist: "Slipknot", title: "Vol. 3: The Subliminal Verses", year: 2004 },
    { artist: "Johnny Cash", title: "American V: A Hundred Highways", year: 2006, notable: true },
    { artist: "Red Hot Chili Peppers", title: "Stadium Arcadium", year: 2006 },
    { artist: "Dixie Chicks", title: "Taking the Long Way", year: 2006, notable: true },
    { artist: "Linkin Park", title: "Minutes to Midnight", year: 2007 },
    { artist: "Neil Diamond", title: "12 Songs", year: 2005 },
    { artist: "Justin Timberlake", title: "FutureSex/LoveSounds", year: 2006 },
    { artist: "Metallica", title: "Death Magnetic", year: 2008, notable: true },
    { artist: "Johnny Cash", title: "American VI: Ain't No Grave", year: 2010 },
    { artist: "Jakob Dylan", title: "Seeing Things", year: 2008 },
    { artist: "Weezer", title: "Weezer (Red Album)", year: 2008 },
    { artist: "Gossip", title: "Music for Men", year: 2009 },
  ],
  "2010s": [
    { artist: "Adele", title: "21", year: 2011, notable: true },
    { artist: "Lana Del Rey", title: "Paradise", year: 2012 },
    { artist: "Kid Rock", title: "Born Free", year: 2010 },
    { artist: "Avett Brothers", title: "I and Love and You", year: 2010 },
    { artist: "Josh Groban", title: "Illuminations", year: 2010 },
    { artist: "Black Sabbath", title: "13", year: 2013, notable: true },
    { artist: "Kanye West", title: "Yeezus", year: 2013, notable: true },
    { artist: "Eminem", title: "The Marshall Mathers LP 2", year: 2013, notable: true },
    { artist: "Lady Gaga", title: "Artpop", year: 2013 },
    { artist: "Ed Sheeran", title: "X", year: 2014 },
    { artist: "AC/DC", title: "Rock or Bust", year: 2014 },
    { artist: "Eminem", title: "Revival", year: 2017 },
    { artist: "The Smashing Pumpkins", title: "Shiny and Oh So Bright, Vol. 1", year: 2018 },
    { artist: "Eminem", title: "Kamikaze", year: 2018 },
    { artist: "Lady Gaga", title: "Joanne", year: 2016 },
    { artist: "Justin Bieber", title: "Purpose", year: 2015 },
    { artist: "James Blake", title: "Assume Form", year: 2019 },
  ],
  "2020s": [
    { artist: "The Strokes", title: "The New Abnormal", year: 2020, notable: true },
    { artist: "Ozzy Osbourne", title: "Ordinary Man", year: 2020, notable: true },
    { artist: "Smashing Pumpkins", title: "Cyr", year: 2020 },
    { artist: "Red Hot Chili Peppers", title: "Unlimited Love", year: 2022, notable: true },
    { artist: "Red Hot Chili Peppers", title: "Return of the Dream Canteen", year: 2022 },
    { artist: "Brandi Carlile", title: "In the Canyon Haze", year: 2022 },
    { artist: "The Black Crowes", title: "Happiness Bastards", year: 2024 },
    { artist: "Santana", title: "Blessings and Miracles", year: 2021 },
  ],
};
