import { Quote } from "../quote";

// Second chunk of quotes (35 quotes)
export const quotesChunk2: Quote[] = [
  {
    text: "The artist doesn't wait for perfect conditions. They work with what they have.",
    chapter: "Action",
    page: 58,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Our greatest strengths often emerge from what we once thought were weaknesses.",
    chapter: "Personal Style",
    page: 139,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Starting with a rigid plan can limit the magical possibilities that emerge in the process.",
    chapter: "Planning",
    page: 84,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Doubt is part of the creative process. The key is not to let it stop you.",
    chapter: "Doubt",
    page: 107,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Comparison is the thief of joy, especially in creative work.",
    chapter: "Comparison",
    page: 133,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The most personal work often becomes the most universal.",
    chapter: "Personal Expression",
    page: 121,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The audience completes the work. Without them, it exists in a vacuum.",
    chapter: "The Audience",
    page: 152,
    likes: 0,
    isLiked: false,
  },
  {
    text: "True innovation often happens at the intersection of seemingly unrelated ideas.",
    chapter: "Innovation",
    page: 115,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The work will teach you how to do it.",
    chapter: "Process",
    page: 39,
    likes: 0,
    isLiked: false,
  },
  {
    text: "We create our most authentic work when we stop trying to impress others.",
    chapter: "Authenticity",
    page: 95,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Sometimes the most important creative choice is what to leave out.",
    chapter: "Editing",
    page: 147,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The master knows that they are always a student.",
    chapter: "Mastery",
    page: 167,
    likes: 0,
    isLiked: false,
  },
  {
    text: "There is no failure, only learning.",
    chapter: "Failure",
    page: 128,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Your inner critic serves a purpose, but don't let it take the driver's seat.",
    chapter: "The Inner Critic",
    page: 104,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Every artist is always beginning again.",
    chapter: "Beginnings",
    page: 27,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The present moment is where all creativity happens.",
    chapter: "Presence",
    page: 62,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The creative process is not linear; it spirals, doubles back, and sometimes leaps forward unexpectedly.",
    chapter: "Process",
    page: 87,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Your work doesn't need to appeal to everyone; it needs to deeply resonate with someone.",
    chapter: "Audience",
    page: 153,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Deadlines are not the enemy of creativity; they're often the catalyst.",
    chapter: "Time Management",
    page: 120,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The space between what you know and what you don't know is where the magic happens.",
    chapter: "Unknown",
    page: 132,
    likes: 0,
    isLiked: false,
  },
  {
    text: "True mastery is knowing which rules to follow and which to break.",
    chapter: "Mastery",
    page: 168,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Enthusiasm is contagious. If you're not excited about your work, no one else will be.",
    chapter: "Enthusiasm",
    page: 94,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The relationship between artist and audience is a conversation, not a monologue.",
    chapter: "The Audience",
    page: 154,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Progress isn't always visible in the moment; trust the process.",
    chapter: "Process",
    page: 88,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The quality of what you consume directly affects the quality of what you create.",
    chapter: "Influences",
    page: 89,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The right environment is as important as the right idea.",
    chapter: "Environment",
    page: 75,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Creative confidence comes from doing the work, not thinking about doing the work.",
    chapter: "Confidence",
    page: 52,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Feedback is valuable, but you must learn which feedback to incorporate and which to ignore.",
    chapter: "Feedback",
    page: 141,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Innovation happens at the edges of disciplines, not at their centers.",
    chapter: "Innovation",
    page: 116,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Making art is not about finding new landscapes, but seeing with new eyes.",
    chapter: "Perception",
    page: 50,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The gap between taste and skill is where growth happens.",
    chapter: "Growth",
    page: 109,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Allow yourself to create bad work. It's the only path to creating good work.",
    chapter: "Permission",
    page: 61,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Routine can be the container that holds the chaos of creativity.",
    chapter: "Routine",
    page: 79,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The most important skill for any artist is the ability to pay attention.",
    chapter: "Attention",
    page: 38,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Trust your instincts, but also learn to question them.",
    chapter: "Instinct",
    page: 96,
    likes: 0,
    isLiked: false,
  }
];
