import { Quote } from "../quote";

// First chunk of quotes (30 quotes)
export const quotesChunk1: Quote[] = [
  {
    text: "The goal is to be as present as possible in the making and allow the result to be what it wants to be.",
    chapter: "On Creating",
    page: 15,
    likes: 0,
    isLiked: false,
  },
  {
    text: "To create is to bring something into existence that wasn't there before. Whether it's a song, a piece of visual art, a cake, or a garden, each creative endeavor adds something new to our world.",
    chapter: "The Source",
    page: 23,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The more we practice any skill, the less we have to think about its mechanics. This allows us to be more present in the moment of making.",
    chapter: "Practice",
    page: 45,
    likes: 0,
    isLiked: false,
  },
  {
    text: "A work of art is never finished. It's abandoned or delivered to a deadline.",
    chapter: "Completion",
    page: 78,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The best ideas often come when we're not trying to come up with them.",
    chapter: "Flow State",
    page: 92,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Creativity isn't a rare gift bestowed upon a select few. It's a natural part of being human.",
    chapter: "The Source",
    page: 18,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The artist's role is to pay attention to the subtle impulses that are easy to miss.",
    chapter: "Attention",
    page: 37,
    likes: 0,
    isLiked: false,
  },
  {
    text: "When we stand back and observe, we make space for something greater than our limited perspectives.",
    chapter: "Observation",
    page: 53,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Intuition is the voice of accumulated wisdom that doesn't need to explain itself.",
    chapter: "Intuition",
    page: 64,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Every process of creation begins with noticing.",
    chapter: "Awareness",
    page: 29,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The limitations we face often become the defining characteristics of our most interesting work.",
    chapter: "Constraints",
    page: 111,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Nothing is created in isolation. Everything builds on what came before.",
    chapter: "Influence",
    page: 88,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Making something new requires forgetting all that we know and embracing not knowing.",
    chapter: "Beginner's Mind",
    page: 42,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Resistance is the signal that we're onto something meaningful.",
    chapter: "Resistance",
    page: 126,
    likes: 0,
    isLiked: false,
  },
  {
    text: "When we create primarily to please others, we disconnect from our authentic voice.",
    chapter: "Authenticity",
    page: 97,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Play is not the opposite of work. At its best, work is play.",
    chapter: "Play",
    page: 73,
    likes: 0,
    isLiked: false,
  },
  {
    text: "True artistic growth means embracing your unique voice rather than chasing trends.",
    chapter: "Artistic Growth",
    page: 112,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The most original work often comes from synthesizing seemingly disparate influences.",
    chapter: "Originality",
    page: 135,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Creative blocks aren't failures; they're invitations to approach your work differently.",
    chapter: "Creative Blocks",
    page: 150,
    likes: 0,
    isLiked: false,
  },
  {
    text: "What makes your work unique is not what you include, but what you have the courage to exclude.",
    chapter: "Editing",
    page: 124,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The distance between where you are and where you want to be is filled by consistent daily practice.",
    chapter: "Practice",
    page: 47,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The quality of your attention determines the quality of your work.",
    chapter: "Attention",
    page: 39,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Sometimes your best work emerges from what initially felt like failure.",
    chapter: "Failure",
    page: 129,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Great art doesn't have to explain itself; it simply has to exist.",
    chapter: "Artistic Expression",
    page: 84,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Vulnerability in your work is not weakness; it's the source of its power.",
    chapter: "Vulnerability",
    page: 101,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The essence of creativity is seeing ordinary things with extraordinary vision.",
    chapter: "Vision",
    page: 56,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Your creative practice should be a sanctuary, not another source of stress.",
    chapter: "Practice",
    page: 48,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Constraints aren't limitations; they're the boundaries that give your work form.",
    chapter: "Constraints",
    page: 112,
    likes: 0,
    isLiked: false,
  },
  {
    text: "Asking better questions leads to better creative solutions than having all the answers.",
    chapter: "Questions",
    page: 77,
    likes: 0,
    isLiked: false,
  },
  {
    text: "The goal isn't perfection; it's authenticity.",
    chapter: "Authenticity",
    page: 98,
    likes: 0,
    isLiked: false,
  }
];
